spring:
  datasource:
    url: jdbc:mysql://localhost:3307/authdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: pass1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true